// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Optional enum
type Test_OEnum int32

const (
	Test_O_ENUM1 Test_OEnum = 0
	Test_O_ENUM2 Test_OEnum = 1
)

// Enum value maps for Test_OEnum.
var (
	Test_OEnum_name = map[int32]string{
		0: "O_ENUM1",
		1: "O_ENUM2",
	}
	Test_OEnum_value = map[string]int32{
		"O_ENUM1": 0,
		"O_ENUM2": 1,
	}
)

func (x Test_OEnum) Enum() *Test_OEnum {
	p := new(Test_OEnum)
	*p = x
	return p
}

func (x Test_OEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Test_OEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Test_OEnum) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Test_OEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Test_OEnum.Descriptor instead.
func (Test_OEnum) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0, 0}
}

type Test struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	D                 float64                `protobuf:"fixed64,1,opt,name=d,proto3" json:"d,omitempty"`
	F                 float32                `protobuf:"fixed32,2,opt,name=f,proto3" json:"f,omitempty"`
	I32               int32                  `protobuf:"varint,3,opt,name=i32,proto3" json:"i32,omitempty"`
	I64               int64                  `protobuf:"varint,4,opt,name=i64,proto3" json:"i64,omitempty"`
	U32               uint32                 `protobuf:"varint,5,opt,name=u32,proto3" json:"u32,omitempty"`
	U64               uint64                 `protobuf:"varint,6,opt,name=u64,proto3" json:"u64,omitempty"`
	T                 bool                   `protobuf:"varint,7,opt,name=t,proto3" json:"t,omitempty"`
	B                 []byte                 `protobuf:"bytes,8,opt,name=b,proto3" json:"b,omitempty"`
	S                 string                 `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	Embedded          *Embedded              `protobuf:"bytes,10,opt,name=embedded,proto3" json:"embedded,omitempty"`
	RepeatedEmbeddeds []*Embedded            `protobuf:"bytes,11,rep,name=repeated_embeddeds,json=repeatedEmbeddeds,proto3" json:"repeated_embeddeds,omitempty"`
	// issue #4
	OptBool       *bool             `protobuf:"varint,12,opt,name=opt_bool,json=optBool,proto3,oneof" json:"opt_bool,omitempty"`
	OptEnum       *Test_OEnum       `protobuf:"varint,13,opt,name=opt_enum,json=optEnum,proto3,enum=Test_OEnum,oneof" json:"opt_enum,omitempty"`
	Map           map[string]string `protobuf:"bytes,14,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetD() float64 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *Test) GetF() float32 {
	if x != nil {
		return x.F
	}
	return 0
}

func (x *Test) GetI32() int32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *Test) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *Test) GetU32() uint32 {
	if x != nil {
		return x.U32
	}
	return 0
}

func (x *Test) GetU64() uint64 {
	if x != nil {
		return x.U64
	}
	return 0
}

func (x *Test) GetT() bool {
	if x != nil {
		return x.T
	}
	return false
}

func (x *Test) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *Test) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *Test) GetEmbedded() *Embedded {
	if x != nil {
		return x.Embedded
	}
	return nil
}

func (x *Test) GetRepeatedEmbeddeds() []*Embedded {
	if x != nil {
		return x.RepeatedEmbeddeds
	}
	return nil
}

func (x *Test) GetOptBool() bool {
	if x != nil && x.OptBool != nil {
		return *x.OptBool
	}
	return false
}

func (x *Test) GetOptEnum() Test_OEnum {
	if x != nil && x.OptEnum != nil {
		return *x.OptEnum
	}
	return Test_O_ENUM1
}

func (x *Test) GetMap() map[string]string {
	if x != nil {
		return x.Map
	}
	return nil
}

type Embedded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             string                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	Embedded      *Embedded              `protobuf:"bytes,2,opt,name=embedded,proto3" json:"embedded,omitempty"`
	OptBool       *bool                  `protobuf:"varint,3,opt,name=opt_bool,json=optBool,proto3,oneof" json:"opt_bool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedded) Reset() {
	*x = Embedded{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedded) ProtoMessage() {}

func (x *Embedded) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedded.ProtoReflect.Descriptor instead.
func (*Embedded) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *Embedded) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *Embedded) GetEmbedded() *Embedded {
	if x != nil {
		return x.Embedded
	}
	return nil
}

func (x *Embedded) GetOptBool() bool {
	if x != nil && x.OptBool != nil {
		return *x.OptBool
	}
	return false
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\"\xd9\x03\n" +
	"\x04Test\x12\f\n" +
	"\x01d\x18\x01 \x01(\x01R\x01d\x12\f\n" +
	"\x01f\x18\x02 \x01(\x02R\x01f\x12\x10\n" +
	"\x03i32\x18\x03 \x01(\x05R\x03i32\x12\x10\n" +
	"\x03i64\x18\x04 \x01(\x03R\x03i64\x12\x10\n" +
	"\x03u32\x18\x05 \x01(\rR\x03u32\x12\x10\n" +
	"\x03u64\x18\x06 \x01(\x04R\x03u64\x12\f\n" +
	"\x01t\x18\a \x01(\bR\x01t\x12\f\n" +
	"\x01b\x18\b \x01(\fR\x01b\x12\f\n" +
	"\x01s\x18\t \x01(\tR\x01s\x12%\n" +
	"\bembedded\x18\n" +
	" \x01(\v2\t.EmbeddedR\bembedded\x128\n" +
	"\x12repeated_embeddeds\x18\v \x03(\v2\t.EmbeddedR\x11repeatedEmbeddeds\x12\x1e\n" +
	"\bopt_bool\x18\f \x01(\bH\x00R\aoptBool\x88\x01\x01\x12+\n" +
	"\bopt_enum\x18\r \x01(\x0e2\v.Test.OEnumH\x01R\aoptEnum\x88\x01\x01\x12 \n" +
	"\x03map\x18\x0e \x03(\v2\x0e.Test.MapEntryR\x03map\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x05OEnum\x12\v\n" +
	"\aO_ENUM1\x10\x00\x12\v\n" +
	"\aO_ENUM2\x10\x01B\v\n" +
	"\t_opt_boolB\v\n" +
	"\t_opt_enum\"l\n" +
	"\bEmbedded\x12\f\n" +
	"\x01s\x18\x01 \x01(\tR\x01s\x12%\n" +
	"\bembedded\x18\x02 \x01(\v2\t.EmbeddedR\bembedded\x12\x1e\n" +
	"\bopt_bool\x18\x03 \x01(\bH\x00R\aoptBool\x88\x01\x01B\v\n" +
	"\t_opt_bool2\x1f\n" +
	"\aTesting\x12\x14\n" +
	"\x04call\x12\x05.Test\x1a\x05.TestB0Z.github.com/ghostiam/protogetter/testdata/protob\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_proto_goTypes = []any{
	(Test_OEnum)(0),  // 0: Test.OEnum
	(*Test)(nil),     // 1: Test
	(*Embedded)(nil), // 2: Embedded
	nil,              // 3: Test.MapEntry
}
var file_test_proto_depIdxs = []int32{
	2, // 0: Test.embedded:type_name -> Embedded
	2, // 1: Test.repeated_embeddeds:type_name -> Embedded
	0, // 2: Test.opt_enum:type_name -> Test.OEnum
	3, // 3: Test.map:type_name -> Test.MapEntry
	2, // 4: Embedded.embedded:type_name -> Embedded
	1, // 5: Testing.call:input_type -> Test
	1, // 6: Testing.call:output_type -> Test
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[0].OneofWrappers = []any{}
	file_test_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
